name       : zeromq
version    : 4.3.0
release    : 5
source     :
    - https://github.com/zeromq/libzmq/releases/download/v4.3.0/zeromq-4.3.0.tar.gz : 8e9c3af6dc5a8540b356697081303be392ade3f014615028b3c896d0148397fd
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : programming
summary    : ZeroMQ lightweight messaging kernel
description: |
    The ZeroMQ lightweight messaging kernel is a library which extends the standard socket interfaces with features traditionally provided by specialised messaging middleware products. ZeroMQ sockets provide an abstraction of asynchronous message queues, multiple messaging patterns, message filtering (subscriptions), seamless access to multiple transport protocols and more.
builddeps  :
    - pkgconfig(openpgm-5.2)
    - pkgconfig(libsodium)
    - asciidoc
patterns   :
    - devel : [/usr/share/man/man3/*]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
