name       : zeromq
version    : 4.2.2
release    : 2
source     :
    - https://github.com/zeromq/libzmq/releases/download/v4.2.2/zeromq-4.2.2.tar.gz : 5b23f4ca9ef545d5bd3af55d305765e3ee06b986263b31967435d285a3e6df6b
license    :
    - GPL-3.0
    - LGPL-3.0
component  : programming
summary    : ZeroMQ lightweight messaging kernel
description: |
    The ZeroMQ lightweight messaging kernel is a library which extends the standard socket interfaces with features traditionally provided by specialised messaging middleware products. ZeroMQ sockets provide an abstraction of asynchronous message queues, multiple messaging patterns, message filtering (subscriptions), seamless access to multiple transport protocols and more.
builddeps  :
    - pkgconfig(libsodium)
    - asciidoc
    - libpgm-devel
    - xmlto
patterns   :
    - devel : [/usr/share/man/man3/*]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
