name       : zeromq
version    : 4.3.4
release    : 10
source     :
    # If you're updating this package you should update cppzmq as well as they need to be updated together
    - https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz : c593001a89f5a85dd2ddf564805deb860e02471171b3f204944857336295c3e5
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : programming
summary    : ZeroMQ lightweight messaging kernel
description: |
    The ZeroMQ lightweight messaging kernel is a library which extends the standard socket interfaces with features traditionally provided by specialised messaging middleware products. ZeroMQ sockets provide an abstraction of asynchronous message queues, multiple messaging patterns, message filtering (subscriptions), seamless access to multiple transport protocols and more.
builddeps  :
    - pkgconfig(openpgm-5.3)
    - pkgconfig(libsodium)
    - asciidoc
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-test_filter_ipc.patch
    %patch -p1 < $pkgfiles/0001-PATCH-If_OPENPGM_FOUND_is_set_link_to_lgpm.patch
    %patch -p1 < $pkgfiles/manpages-instead-of-html-pages.patch
    
    sed -i 's/openpgm-5.2/openpgm-5.3/' CMakeLists.txt

    %cmake_ninja -DBUILD_STATIC=OFF \
                 -DWITH_LIBBSD=OFF \
                 -DWITH_DOCS=OFF \
                 -DWITH_OPENPGM=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
