name       : zeromq
version    : 4.2.5
release    : 4
source     :
    - https://github.com/zeromq/libzmq/releases/download/v4.2.5/zeromq-4.2.5.tar.gz : cc9090ba35713d59bb2f7d7965f877036c49c5558ea0c290b0dcc6f2a17e489f
license    :
    - GPL-3.0
    - LGPL-3.0
component  : programming
summary    : ZeroMQ lightweight messaging kernel
description: |
    The ZeroMQ lightweight messaging kernel is a library which extends the standard socket interfaces with features traditionally provided by specialised messaging middleware products. ZeroMQ sockets provide an abstraction of asynchronous message queues, multiple messaging patterns, message filtering (subscriptions), seamless access to multiple transport protocols and more.
builddeps  :
    - pkgconfig(libsodium)
    - asciidoc
    - libpgm-devel
    - xmlto
patterns   :
    - devel : [/usr/share/man/man3/*]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
