name       : zeromq
version    : 4.3.1
release    : 6
source     :
    - https://github.com/zeromq/libzmq/releases/download/v4.3.1/zeromq-4.3.1.tar.gz : bcbabe1e2c7d0eec4ed612e10b94b112dd5f06fcefa994a0c79a45d835cd21eb
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : programming
summary    : ZeroMQ lightweight messaging kernel
description: |
    The ZeroMQ lightweight messaging kernel is a library which extends the standard socket interfaces with features traditionally provided by specialised messaging middleware products. ZeroMQ sockets provide an abstraction of asynchronous message queues, multiple messaging patterns, message filtering (subscriptions), seamless access to multiple transport protocols and more.
builddeps  :
    - pkgconfig(openpgm-5.2)
    - pkgconfig(libsodium)
    - asciidoc
patterns   :
    - devel : [/usr/share/man/man3/*]
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-test_filter_ipc.patch

    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
